Repository octobercms/library, pull requests merged in 2018-03, with the labels that each got.

#302 Fix escaping of multiline values in INI
  src/Parse/Ini.php
  tests/Parse/IniTest.php
  tests/fixtures/parse/multilines-value.ini
Labels: Status: Review Needed, Type: Maintenance

#316 Add ability to use array validation for attachMany
  src/Database/Relations/AttachMany.php
  src/Database/Traits/Validation.php
Labels: Status: Accepted, Type: Enhancement

#308 Simplify retrieval of CMS objects to one cache request instead of two
  composer.json
  src/Halcyon/Builder.php
  src/Halcyon/HalcyonServiceProvider.php
  src/Halcyon/MemoryCache.php
  src/Halcyon/MemoryCacheManager.php
  src/Halcyon/MemoryRepository.php
  tests/Halcyon/MemoryRepositoryTest.php
Labels: Status: Completed, Type: Enhancement
