Repository octobercms/library, pull requests merged in 2018-06, with the labels that each got.

#325 Fixes section parser.
  src/Halcyon/Processors/SectionParser.php
  tests/Halcyon/SectionParserTest.php
Labels: Status: Response Needed, Type: Maintenance

#326 Error in SectionParserTest
  tests/Halcyon/SectionParserTest.php
Labels: Type: Maintenance

#293 Make extendClassWith support dot notation
  src/Extension/ExtendableTrait.php
  tests/Extension/ExtendableTest.php
Labels: Type: Maintenance

#330 Regenerate slugs if missing on existing models.
  src/Database/Traits/Sluggable.php
Labels: Type: Maintenance

#328 Enhance deferred_bindings table query performance
  src/Database/Relations/DeferOneOrMany.php
Labels: Priority: Medium, Status: Accepted, Status: Response Needed, Type: Conceptual Enhancement
