Repository octobercms/library, pull requests merged in 2019-05, with the labels that each got.

#398 Removed spaces from stubs so str_replace will place correct values
  src/Scaffold/Console/formwidget/javascript.stub
  src/Scaffold/Console/formwidget/stylesheet.stub
Labels: Status: Review Needed, Type: Maintenance

#399 Typo fix
  src/Database/Attach/Resizer.php
Labels: Type: Maintenance

#400 Add missing "fit" mode in class' DocBlock
  src/Database/Attach/Resizer.php
Labels: Status: Completed, Type: Maintenance

#401 Disable in-memory cache repository in CLI by default
  src/Halcyon/MemoryCacheManager.php
Labels: Status: Completed, Type: Enhancement

#402 Initial Laravel auth compatibility
  src/Auth/Manager.php
  src/Auth/Models/User.php
Labels: Type: Maintenance

#386 Typo fix.
  build/git-subsplit.sh
Labels: Status: Completed, Type: Maintenance

#396 Resizer transparency fix
  src/Database/Attach/Resizer.php
  tests/fixtures/resizer/target/testCrop10x15.gif
  tests/fixtures/resizer/target/testResize0x20.gif
  tests/fixtures/resizer/target/testResize20x0.gif
  tests/fixtures/resizer/target/testResizeAutoPortrait50.gif
  tests/fixtures/resizer/target/testResizeFitPortrait30x30.gif
  tests/fixtures/resizer/target/testResizeLandscape10x1.gif
  tests/fixtures/resizer/target/testResizePortrait1x10.gif
Labels: Type: Maintenance

#387 Revert 'HasMany memory performance solution'
  src/Database/Relations/HasMany.php
Labels: Type: Maintenance

#404 Implement "http_build_url" polyfill / wrapper into core
  src/Foundation/Application.php
  src/Router/RoutingServiceProvider.php
  src/Router/UrlGenerator.php
  src/Support/Facades/Url.php
  src/Support/helpers.php
  tests/Support/UrlGeneratorTest.php
Labels: Status: Review Needed, Testing Needed, Type: Enhancement
