Repository octobercms/library, pull requests merged in 2019-01, with the labels that each got.

#370 Not halting validation when returning false from model.beforeValidate
  src/Database/Traits/Validation.php
Labels: Type: Maintenance

#372 Reverted newlines and zeros
  src/Parse/Assetic/StylesheetMinify.php
Labels: Status: Completed, Type: Maintenance

#373 StylesheetMinify.php Fix
  src/Parse/Assetic/StylesheetMinify.php
Labels: Status: Completed, Type: Maintenance

#374 Add YAML file being parsed to syntax error message
  .travis.yml
  src/Parse/Yaml.php
Labels: Status: Completed, Type: Maintenance

#371 Added validateUserModel method
  src/Auth/Manager.php
Labels: Status: Completed, Type: Maintenance

#375 Add get_class_methods() equivalent for extendable classes
  src/Extension/ExtendableTrait.php
  tests/Extension/ExtendableTest.php
Labels: Status: Completed, Type: Enhancement
