Repository octobercms/library, pull requests merged in 2019-09, with the labels that each got.

#384 Fix Database/Updater.php script that parses the full classname from a file.
  composer.json
  src/Database/Updater.php
  tests/Database/UpdaterTest.php
  tests/fixtures/Database/SampleClass.php
Labels: Status: Completed, Type: Maintenance

#427 Improved .gif resizing in Resizer class
  src/Database/Attach/Resizer.php
  tests/Database/Attach/ResizerTest.php
  tests/fixtures/resizer/target/testResize0x20.gif
  tests/fixtures/resizer/target/testResize20x0.gif
  tests/fixtures/resizer/target/testResizeAutoPortrait50.gif
  tests/fixtures/resizer/target/testResizeFitPortrait30x30.gif
  tests/fixtures/resizer/target/testResizeLandscape10x1.gif
  tests/fixtures/resizer/target/testResizePortrait1x10.gif
Labels: Status: Review Needed, Type: Maintenance

#425 Fixed Error in Comment
  src/Network/Http.php
  src/Network/README.md
Labels: Status: Completed, Type: Maintenance

#419 Add yaml parseFile caching
  src/Parse/Yaml.php
Labels: Status: Completed, Type: Enhancement

#429 Fix missing CURLOPT values
  src/Network/Http.php
  tests/Network/HttpTest.php
Labels: Status: Completed, Type: Bug, Type: Maintenance

#430 Add GitHub Actions for Library
  .github/workflows/code-quality-pr.yaml
  .github/workflows/code-quality-push.yaml
  .github/workflows/tests.yml
  .github/workflows/wrong-branch-notification.yaml
  .travis.yml
Labels: Status: Completed, Type: Maintenance
