Repository octobercms/library, pull requests merged in 2019-04, with the labels that each got.

#390 Fixed phpdoc return type for lists() method
  src/Database/Builder.php
Labels: Type: Maintenance

#392 Inject role="form" to allow accessibility standards.
  src/Html/FormBuilder.php
Labels: Status: Completed, Type: Maintenance

#383 Convert array notated fields to dot notation on validation
  src/Database/Traits/Validation.php
  src/Halcyon/Traits/Validation.php
  tests/Database/Traits/ValidationTest.php
  tests/Halcyon/ValidationTraitTest.php
  tests/TestCase.php
Labels: Status: Review Needed, Type: Maintenance

#394 Add missing svg mimetype
  src/Database/Attach/File.php
Labels: Status: Completed, Type: Maintenance

#363 Allow optional wildcard parameteres
  src/Router/Helper.php
Labels: Status: Completed, Type: Enhancement
