Repository octobercms/library, pull requests merged in 2019-06, with the labels that each got.

#356 Halcyon DbDatasource
  src/Halcyon/Datasource/Datasource.php
  src/Halcyon/Datasource/DatasourceInterface.php
  src/Halcyon/Datasource/DbDatasource.php
  src/Halcyon/Datasource/FileDatasource.php
  src/Halcyon/Model.php
Labels: Priority: Medium, Status: In Progress, Type: Enhancement

#406 Various improvements to File handling logic
  src/Database/Attach/File.php
Labels: Status: Completed, Type: Maintenance

#408 improve AddDynamicPoperty test
  tests/Halcyon/ModelTest.php
Labels: Status: Revision Needed, Type: Maintenance

#405 Fix douple decoding of jsonable attributes
  src/Database/Model.php
Labels: Status: Completed, Type: Maintenance
