Repository octobercms/library, pull requests merged in 2020-07, with the labels that each got.

#499 All non-null values should be encrypted
  composer.json
  src/Database/Traits/Encryptable.php
  tests/Database/Traits/EncryptableTest.php
Labels: Status: Completed, Type: Maintenance

#491 Allow deep symlinks when translating paths to local URLs
  src/Filesystem/Filesystem.php
Labels: Status: Completed, Type: Enhancement

#504 Http docblock asks for an array, when really what it wants is a callable
  src/Network/Http.php
Labels: Status: Completed, Type: Maintenance

#505 Added HtmlBuilder test with umlauts to test for proper encoding
  tests/Html/HtmlBuilderTest.php
Labels: Status: Completed, Type: Maintenance

#508 Improvements to cookie value validation
  src/Cookie/CookieValuePrefix.php
  src/Cookie/Middleware/EncryptCookies.php
Labels: Testing Needed, Type: Maintenance

#507 Fix input method return type
  src/Support/helpers.php
Labels: Status: Completed, Type: Maintenance
