Repository octobercms/library, pull requests merged in 2020-01, with the labels that each got.

#451 Make translator implementation compatible with translator interface
  src/Translation/Translator.php
Labels: Status: Review Needed, Type: Maintenance

#454 Inject queue name into auto-created Mailables.
  src/Mail/Mailer.php
Labels: Status: Completed, Type: Maintenance

#443 [Laravel 6] Bring code to a state where unit tests pass
  .github/workflows/tests.yml
  .gitignore
  composer.json
  src/Database/Attach/File.php
  src/Database/Attach/Resizer.php
  src/Database/Concerns/HasRelationships.php
  src/Database/Relations/MorphTo.php
  src/Database/Traits/Validation.php
  src/Foundation/Bootstrap/LoadEnvironmentVariables.php
  src/Halcyon/MemoryRepository.php
  src/Halcyon/Traits/Validation.php
  src/Parse/Assetic/FilesystemCache.php
  src/Parse/Assetic/JavascriptImporter.php
  src/Parse/Assetic/LessCompiler.php
  src/Parse/Assetic/ScssCompiler.php
  src/Parse/Assetic/StylesheetMinify.php
  src/Support/Facade.php
  src/Support/Facades/Input.php
  src/Support/README.md
  src/Support/helpers.php
  tests/Config/ConfigWriterTest.php
  tests/Database/Attach/ResizerTest.php
  tests/Database/SortableTest.php
  tests/Database/Traits/SluggableTest.php
  tests/Database/UpdaterTest.php
  tests/Events/DispatcherTest.php
  tests/Extension/ExtendableTest.php
  tests/Halcyon/MemoryRepositoryTest.php
  tests/Halcyon/ModelTest.php
  tests/Halcyon/SectionParserTest.php
  tests/Html/HtmlHelperTest.php
  tests/Network/HttpTest.php
  tests/Parse/Assetic/MockAsset.php
  tests/Support/EmitterTest.php
  tests/Support/StrTest.php
  tests/TestCase.php
  tests/Translation/TranslatorTest.php
Labels: Status: Review Needed, Type: Enhancement

#458 Check current file info before using it
  src/Parse/Assetic/Less/lib/Less/Tree/Import.php
Labels: Type: Maintenance
