Repository octobercms/library, pull requests merged in 2021-01, with the labels that each got.

#549 Add trusted hosts support to library
  src/Foundation/Http/Kernel.php
  src/Foundation/Http/Middleware/CheckForTrustedHost.php
  src/Http/Middleware/TrustHosts.php
  tests/Foundation/Http/Middleware/CheckForTrustedHostTest.php
Labels: Status: Completed, Type: Enhancement

#502 Fix file attachments eager load with PostgreSQL
  src/Database/Attach/File.php
  src/Database/Concerns/HasRelationships.php
  src/Database/Relations/AttachMany.php
  src/Database/Relations/AttachOne.php
Labels: Testing Needed, Type: Maintenance

#460 Add getRelationTypeDefinition methods
  src/Database/Concerns/HasRelationships.php
  tests/Database/Concerns/HasRelationshipsTest.php
Labels: Status: Completed, Type: Enhancement

#556 Fix getRelationType method
  src/Database/Concerns/HasRelationships.php
  tests/Database/RelationsTest.php
Labels: Status: Completed, Type: Maintenance
